//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalmApp.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int PackageId { get; set; }
        public int ServiceId { get; set; }
        public string Duration { get; set; }
        public string PackageName { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
